# Generated by Django 5.1.7 on 2025-03-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_idade_paciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(default='00000000', max_length=12),
        ),
    ]
