# Generated by Django 5.1.7 on 2025-03-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
